# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [ ]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [2]:
#todo: 
import numpy as np
#Creamos el array de 0 a 9
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [8]:
#todo:
import numpy as np
array_dos = np.zeros(5)
array_dos[2] = 5

print(array_dos)

[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [10]:
#todo: 
import numpy as np
matriz = np.random.rand(3,3)
print(matriz)

[[0.77852241 0.91428134 0.53570792]
 [0.46083247 0.17774074 0.91452246]
 [0.3007597  0.03287169 0.49626264]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [13]:
#todo:
import numpy as np
import random

arr = np.array([10,20,30,40,50])
print("Array Original: ", arr)
#Sumaremos 5 a cada elemento del array
arr_suma = arr + 5
#Mostramos el array sumando 5
print("Array sumado 5: ", arr_suma)

#2 - multiplicamos por numero aleatorio.
multiplica = random.randint(1,10)
arr_prod = arr_suma * multiplica
print("El numero random es: ", multiplica)
#Mostramos el array multiplicado por un número Random.
print("Array multiplicado por N° random", arr_prod) 


Array Original:  [10 20 30 40 50]
Array sumado 5:  [15 25 35 45 55]
El numero random es:  2
Array multiplicado por N° random [ 30  50  70  90 110]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:

**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 

